/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import easyloto.Jogo;
import easyloto.Loteria;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Note
 */
public class Volante extends javax.swing.JFrame {

    /**
     * Creates new form Volante
     */
    private ArrayList<Integer> BtSelecionados = new ArrayList();
    static Loteria loteria = new Loteria();
    
    private int IdAtual = 0;
    
    public Volante() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tb_09 = new javax.swing.JToggleButton();
        tb_08 = new javax.swing.JToggleButton();
        tb_07 = new javax.swing.JToggleButton();
        tb_06 = new javax.swing.JToggleButton();
        tb_01 = new javax.swing.JToggleButton();
        tb_03 = new javax.swing.JToggleButton();
        tb_04 = new javax.swing.JToggleButton();
        tb_05 = new javax.swing.JToggleButton();
        tb_10 = new javax.swing.JToggleButton();
        tb_19 = new javax.swing.JToggleButton();
        tb_18 = new javax.swing.JToggleButton();
        tb_17 = new javax.swing.JToggleButton();
        tb_16 = new javax.swing.JToggleButton();
        tb_12 = new javax.swing.JToggleButton();
        tb_13 = new javax.swing.JToggleButton();
        tb_14 = new javax.swing.JToggleButton();
        tb_15 = new javax.swing.JToggleButton();
        tb_20 = new javax.swing.JToggleButton();
        tb_21 = new javax.swing.JToggleButton();
        tb_25 = new javax.swing.JToggleButton();
        tb_24 = new javax.swing.JToggleButton();
        tb_23 = new javax.swing.JToggleButton();
        tb_22 = new javax.swing.JToggleButton();
        tb_11 = new javax.swing.JToggleButton();
        tb_02 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jb_novojogo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_dezenas = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lb_qntdez = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lb_18 = new javax.swing.JLabel();
        lb_17 = new javax.swing.JLabel();
        lb_15 = new javax.swing.JLabel();
        lb_16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_resultados = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153)));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 1, true));

        tb_09.setText("09");
        tb_09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_09ActionPerformed(evt);
            }
        });

        tb_08.setText("08");
        tb_08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_08ActionPerformed(evt);
            }
        });

        tb_07.setText("07");
        tb_07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_07ActionPerformed(evt);
            }
        });

        tb_06.setText("06");
        tb_06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_06ActionPerformed(evt);
            }
        });

        tb_01.setText("01");
        tb_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_01ActionPerformed(evt);
            }
        });

        tb_03.setText("03");
        tb_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_03ActionPerformed(evt);
            }
        });

        tb_04.setText("04");
        tb_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_04ActionPerformed(evt);
            }
        });

        tb_05.setText("05");
        tb_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_05ActionPerformed(evt);
            }
        });

        tb_10.setText("10");
        tb_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_10ActionPerformed(evt);
            }
        });

        tb_19.setText("19");
        tb_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_19ActionPerformed(evt);
            }
        });

        tb_18.setText("18");
        tb_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_18ActionPerformed(evt);
            }
        });

        tb_17.setText("17");
        tb_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_17ActionPerformed(evt);
            }
        });

        tb_16.setText("16");
        tb_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_16ActionPerformed(evt);
            }
        });

        tb_12.setText("12");
        tb_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_12ActionPerformed(evt);
            }
        });

        tb_13.setText("13");
        tb_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_13ActionPerformed(evt);
            }
        });

        tb_14.setText("14");
        tb_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_14ActionPerformed(evt);
            }
        });

        tb_15.setText("15");
        tb_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_15ActionPerformed(evt);
            }
        });

        tb_20.setText("20");
        tb_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_20ActionPerformed(evt);
            }
        });

        tb_21.setText("21");
        tb_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_21ActionPerformed(evt);
            }
        });

        tb_25.setText("25");
        tb_25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_25ActionPerformed(evt);
            }
        });

        tb_24.setText("24");
        tb_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_24ActionPerformed(evt);
            }
        });

        tb_23.setText("23");
        tb_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_23ActionPerformed(evt);
            }
        });

        tb_22.setText("22");
        tb_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_22ActionPerformed(evt);
            }
        });

        tb_11.setText("11");
        tb_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_11ActionPerformed(evt);
            }
        });

        tb_02.setText("02");
        tb_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tb_01, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_06, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tb_02, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_07, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tb_03, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_08, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tb_04, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_09, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tb_05, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_01, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_03, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_04, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_05, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_02, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_07, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_08, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_06, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_09, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/easytopo.png"))); // NOI18N

        jb_novojogo.setBackground(new java.awt.Color(255, 0, 0));
        jb_novojogo.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jb_novojogo.setForeground(new java.awt.Color(255, 255, 255));
        jb_novojogo.setText("Fazer este jogo");
        jb_novojogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_novojogoMouseEntered(evt);
            }
        });
        jb_novojogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novojogoActionPerformed(evt);
            }
        });

        ta_dezenas.setEditable(false);
        ta_dezenas.setColumns(20);
        ta_dezenas.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        ta_dezenas.setRows(2);
        ta_dezenas.setWrapStyleWord(true);
        ta_dezenas.setLineWrap(true);
        jScrollPane1.setViewportView(ta_dezenas);

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel3.setText("Quantidade de dezenas:");

        lb_qntdez.setBackground(new java.awt.Color(255, 255, 255));
        lb_qntdez.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_novojogo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_qntdez, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_qntdez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_novojogo)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 0, 153));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 1, true));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153)));

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel8.setText("Resultados:");

        jLabel13.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel13.setText("Com 16 dezenas:");

        jLabel9.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel9.setText("Com 15 dezenas:");

        jLabel14.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel14.setText("Com 17 dezenas:");

        jLabel15.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel15.setText("Com 18 dezenas:");

        lb_18.setBackground(new java.awt.Color(255, 255, 255));
        lb_18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_18.setText("0");
        lb_18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_17.setBackground(new java.awt.Color(255, 255, 255));
        lb_17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_17.setText("0");
        lb_17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_15.setBackground(new java.awt.Color(255, 255, 255));
        lb_15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_15.setText("0");
        lb_15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_16.setBackground(new java.awt.Color(255, 255, 255));
        lb_16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_16.setText("0");
        lb_16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel17.setText("TOTAL:");

        lb_total.setBackground(new java.awt.Color(255, 255, 255));
        lb_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_total.setText("0");
        lb_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBackground(new java.awt.Color(153, 0, 102));

        jLabel6.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantidade de jogos feitos:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_18, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_17, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Inserir dezenas sorteadas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ta_resultados.setColumns(20);
        ta_resultados.setRows(5);
        ta_resultados.setWrapStyleWord(true);
        ta_resultados.setLineWrap(true);
        jScrollPane3.setViewportView(ta_resultados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Volante.this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tb_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_02ActionPerformed
        if (tb_02.isSelected()) {
            adicionaBtSelecionado(2);
        } else {
           removeBtSelecionado(2);
        }  
    }//GEN-LAST:event_tb_02ActionPerformed

    private void tb_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_11ActionPerformed
        if (tb_11.isSelected()) {
            adicionaBtSelecionado(11);
        } else {
           removeBtSelecionado(11);
        } 
    }//GEN-LAST:event_tb_11ActionPerformed

    private void tb_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_22ActionPerformed
        if (tb_22.isSelected()) {
            adicionaBtSelecionado(22);
        } else {
           removeBtSelecionado(22);
        } 
    }//GEN-LAST:event_tb_22ActionPerformed

    private void tb_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_23ActionPerformed
        if (tb_23.isSelected()) {
            adicionaBtSelecionado(23);
        } else {
           removeBtSelecionado(23);
        } 
    }//GEN-LAST:event_tb_23ActionPerformed

    private void tb_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_24ActionPerformed
        if (tb_24.isSelected()) {
            adicionaBtSelecionado(24);
        } else {
           removeBtSelecionado(24);
        } 
    }//GEN-LAST:event_tb_24ActionPerformed

    private void tb_25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_25ActionPerformed
        if (tb_25.isSelected()) {
            adicionaBtSelecionado(25);
        } else {
           removeBtSelecionado(25);
        } 
    }//GEN-LAST:event_tb_25ActionPerformed

    private void tb_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_21ActionPerformed
        if (tb_21.isSelected()) {
            adicionaBtSelecionado(21);
        } else {
           removeBtSelecionado(21);
        } 
    }//GEN-LAST:event_tb_21ActionPerformed

    private void tb_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_20ActionPerformed
        if (tb_20.isSelected()) {
            adicionaBtSelecionado(20);
        } else {
           removeBtSelecionado(20);
        } 
    }//GEN-LAST:event_tb_20ActionPerformed

    private void tb_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_15ActionPerformed
        if (tb_15.isSelected()) {
            adicionaBtSelecionado(15);
        } else {
           removeBtSelecionado(15);
        } 
    }//GEN-LAST:event_tb_15ActionPerformed

    private void tb_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_14ActionPerformed
        if (tb_14.isSelected()) {
            adicionaBtSelecionado(14);
        } else {
           removeBtSelecionado(14);
        } 
    }//GEN-LAST:event_tb_14ActionPerformed

    private void tb_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_13ActionPerformed
        if (tb_13.isSelected()) {
            adicionaBtSelecionado(13);
        } else {
           removeBtSelecionado(13);
        } 
    }//GEN-LAST:event_tb_13ActionPerformed

    private void tb_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_12ActionPerformed
        if (tb_12.isSelected()) {
            adicionaBtSelecionado(12);
        } else {
           removeBtSelecionado(12);
        } 
    }//GEN-LAST:event_tb_12ActionPerformed

    private void tb_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_16ActionPerformed
        if (tb_16.isSelected()) {
            adicionaBtSelecionado(16);
        } else {
           removeBtSelecionado(16);
        } 
    }//GEN-LAST:event_tb_16ActionPerformed

    private void tb_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_17ActionPerformed
        if (tb_17.isSelected()) {
            adicionaBtSelecionado(17);
        } else {
           removeBtSelecionado(17);
        } 
    }//GEN-LAST:event_tb_17ActionPerformed

    private void tb_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_18ActionPerformed
        if (tb_18.isSelected()) {
            adicionaBtSelecionado(18);
        } else {
           removeBtSelecionado(18);
        } 
    }//GEN-LAST:event_tb_18ActionPerformed

    private void tb_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_19ActionPerformed
        if (tb_19.isSelected()) {
            adicionaBtSelecionado(19);
        } else {
           removeBtSelecionado(19);
        } 
    }//GEN-LAST:event_tb_19ActionPerformed

    private void tb_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_10ActionPerformed
        if (tb_10.isSelected()) {
            adicionaBtSelecionado(10);
        } else {
           removeBtSelecionado(10);
        } 
    }//GEN-LAST:event_tb_10ActionPerformed

    private void tb_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_05ActionPerformed
        if (tb_05.isSelected()) {
            adicionaBtSelecionado(5);
        } else {
           removeBtSelecionado(5);
        }
    }//GEN-LAST:event_tb_05ActionPerformed

    private void tb_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_04ActionPerformed
        if (tb_04.isSelected()) {
            adicionaBtSelecionado(4);
        } else {
           removeBtSelecionado(4);
        }
    }//GEN-LAST:event_tb_04ActionPerformed

    private void tb_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_03ActionPerformed
        if (tb_03.isSelected()) {
            adicionaBtSelecionado(3);
        } else {
           removeBtSelecionado(3);
        }
    }//GEN-LAST:event_tb_03ActionPerformed

    private void tb_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_01ActionPerformed
        if (tb_01.isSelected()) {
            adicionaBtSelecionado(1);
        } else {
           removeBtSelecionado(1);
        }       
    }//GEN-LAST:event_tb_01ActionPerformed

    private void tb_06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_06ActionPerformed
        if (tb_06.isSelected()) {
            adicionaBtSelecionado(6);
        } else {
           removeBtSelecionado(6);
        } 
    }//GEN-LAST:event_tb_06ActionPerformed

    private void tb_07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_07ActionPerformed
        if (tb_07.isSelected()) {
            adicionaBtSelecionado(7);
        } else {
           removeBtSelecionado(7);
        } 
    }//GEN-LAST:event_tb_07ActionPerformed

    private void tb_08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_08ActionPerformed
        if (tb_08.isSelected()) {
            adicionaBtSelecionado(8);
        } else {
           removeBtSelecionado(8);
        } 
    }//GEN-LAST:event_tb_08ActionPerformed

    private void tb_09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_09ActionPerformed
        if (tb_09.isSelected()) {
            adicionaBtSelecionado(9);
        } else {
           removeBtSelecionado(9);
        } 
    }//GEN-LAST:event_tb_09ActionPerformed

    private void jb_novojogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novojogoActionPerformed
        if((BtSelecionados.size()>=15) && (BtSelecionados.size()<=18)){
            Jogo j = new Jogo();
            IdAtual++;
            j.setIdJogo(IdAtual);
            j.setDezenasAposta(BtSelecionados);
            j.setQntDezenas(BtSelecionados.size());
            
            if (j.getQntDezenas()==15) {
                loteria.setQnt_15(1);
                lb_15.setText(Integer.toString(loteria.getQnt_15()));
            } else {
                if (j.getQntDezenas() == 16) {
                    loteria.setQnt_16(1);
                    lb_16.setText(Integer.toString(loteria.getQnt_16()));
                } else {
                    if (j.getQntDezenas() == 17) {
                        loteria.setQnt_17(1);
                        lb_17.setText(Integer.toString(loteria.getQnt_17()));
                    } else {
                        loteria.setQnt_18(1);
                        lb_18.setText(Integer.toString(loteria.getQnt_18()));
                    }
                }
            }
            
            System.out.println("Id do Jogo: "+j.getIdJogo());
            loteria.imprimeArray(j.getDezenasAposta());
            
            loteria.getListaJogos().add(j);
            lb_total.setText(Integer.toString(loteria.getListaJogos().size()));
        }else{
            //JOptionPane.showMessageDialog(null,"Jogo não cadastrado! Escolha 15, 16, 17 ou 18 dezenas");
            JOptionPane.showMessageDialog(null, "Escolha 15, 16, 17 ou 18 dezenas", "Jogo não cadastrado!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jb_novojogoActionPerformed

    private void jb_novojogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_novojogoMouseEntered
        ta_dezenas.setText("");
        for (int i = 0; i < BtSelecionados.size(); i++) {
            if (BtSelecionados.get(i)<10) {
                ta_dezenas.setText(ta_dezenas.getText()+"0"+BtSelecionados.get(i)+" ");
            } else {
                ta_dezenas.setText(ta_dezenas.getText()+BtSelecionados.get(i)+" ");
            }   
        }
    }//GEN-LAST:event_jb_novojogoMouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new DezenasSorteadas().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loteria.varreListaJogos(loteria.getListaJogos());
        
        ta_resultados.setText("Total de Jogos Premiados com 15 dezenas: "+ loteria.getJogosPremiados().size());
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adicionaBtSelecionado(int valor){
        BtSelecionados.add(valor);
        lb_qntdez.setText(Integer.toString(BtSelecionados.size()));
    }
    
    private void removeBtSelecionado(int valor){
        for (int i = 0; i < BtSelecionados.size(); i++) {
            if (BtSelecionados.get(i).equals(valor)) {
                BtSelecionados.remove(i);
                lb_qntdez.setText(Integer.toString(BtSelecionados.size()));
            }
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb_novojogo;
    private javax.swing.JLabel lb_15;
    private javax.swing.JLabel lb_16;
    private javax.swing.JLabel lb_17;
    private javax.swing.JLabel lb_18;
    private javax.swing.JLabel lb_qntdez;
    private javax.swing.JLabel lb_total;
    private javax.swing.JTextArea ta_dezenas;
    private javax.swing.JTextArea ta_resultados;
    private javax.swing.JToggleButton tb_01;
    private javax.swing.JToggleButton tb_02;
    private javax.swing.JToggleButton tb_03;
    private javax.swing.JToggleButton tb_04;
    private javax.swing.JToggleButton tb_05;
    private javax.swing.JToggleButton tb_06;
    private javax.swing.JToggleButton tb_07;
    private javax.swing.JToggleButton tb_08;
    private javax.swing.JToggleButton tb_09;
    private javax.swing.JToggleButton tb_10;
    private javax.swing.JToggleButton tb_11;
    private javax.swing.JToggleButton tb_12;
    private javax.swing.JToggleButton tb_13;
    private javax.swing.JToggleButton tb_14;
    private javax.swing.JToggleButton tb_15;
    private javax.swing.JToggleButton tb_16;
    private javax.swing.JToggleButton tb_17;
    private javax.swing.JToggleButton tb_18;
    private javax.swing.JToggleButton tb_19;
    private javax.swing.JToggleButton tb_20;
    private javax.swing.JToggleButton tb_21;
    private javax.swing.JToggleButton tb_22;
    private javax.swing.JToggleButton tb_23;
    private javax.swing.JToggleButton tb_24;
    private javax.swing.JToggleButton tb_25;
    // End of variables declaration//GEN-END:variables
}
